//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int ProgressID { get; set; }
        public string ProgressDetail { get; set; }
        public int ProjectID { get; set; }
        public int ReportID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Report Report { get; set; }
    }
}
